export const Muscles = [
    'Chest','Back','Shoulders','Triceps','Biceps','Legs'
]

export const Exercises = [
    {
        id: 'bench-press',
        title: 'Bench Press',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/UZi_zwL3Oq0'
    },
    {
        id: 'incline-press',
        title: 'Incline Press',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink:'https://www.youtube.com/embed/11gY7Q5D5wo'
    },
    {
        id: 'decline-press',
        title: 'Decline Press',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink:'https://www.youtube.com/embed/qX2o_FiQeDg'
    },
    {
        id: 'pec-deck-fly',
        title: 'Pec Deck Fly',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink:'https://www.youtube.com/embed/Qr7dstCeYtw'
    },
    {
        id: 'push-up',
        title: 'Push Up',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink:'https://www.youtube.com/embed/SOnxS6Bwarg'
    },
    {
        id: 'cable-crossover',
        title: 'Cable Crossover',
        sets: 3,
        reps: 12,
        muscle:'Chest',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 15',
        videolink:'https://www.youtube.com/embed/taI4XduLpTk'
    },
    {
        id: 'wide-grip-lat-pull-down',
        title: 'Wide Grip Lat Pull Down',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/lueEJGjTuPQ'
    },
    {
        id: 'barbell-deadlift',
        title: 'Barbell Deadlift',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/sLqn0uP6iCU'
    },
    {
        id: 'dumbbell-row',
        title: 'Dumbell Row',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/l_qeCPJMU9o'
    },
    {
        id: 'chest-supported-dumbbell-rows',
        title: 'Chest Supported Dumbbell Rows',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/nl2MnK1i504'
    },
    {
        id: 'close-grip-lat-pull-down',
        title: 'Close Grip Lat Pull Down',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/neP32qCyPbQ'
    },
    {
        id: 'pullups',
        title: 'Pull Ups',
        sets: 4,
        reps: 12,
        muscle:'Back',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '5 X 15',
        videolink: 'https://www.youtube.com/embed/Es_psmnCn20'
    },
    {
        id: 'dumbbell-overhead-press',
        title: 'Dumbbell Overhead Press',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/Gh6erNfGOYw'
    },
    {
        id: 'front-raise',
        title: 'Front Raise',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/gzDawZwDC6Y'
    },
    {
        id: 'lateral-raise',
        title: 'Lateral Raise',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/geenhiHju-o'
    },
    {
        id: 'reverse-fly',
        title: 'Reverse Fly',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/T1U3yZne1jw'
    },
    {
        id: 'barbell standing row',
        title: 'Barbell Standing Row',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/nIJGvsdNtFE'
    },
    {
        id: 'arnold press',
        title: 'Arnold Press',
        sets: 3,
        reps: 12,
        muscle:'Shoulders',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 x 10-12',
        advanced: '5 x 15',
        videolink: 'https://www.youtube.com/embed/6Z15_WdXmVw'
    },
    {
        id: 'skull-crusher',
        title: 'Skull Crusher',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/d_KZxkY_0cM'
    },
    {
        id: 'diamond-push-up',
        title: 'Diamond Push Up',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/J0DnG1_S92I'
    },
    {
        id: 'dumbbell-overhead-extentions',
        title: 'Dumbbell Overhead Extentions',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/YbX7Wd8jQ-Q'
    },
    {
        id: 'barbell-overhead-extentions',
        title: 'Barbell Overhead Extentions',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/szES3xIzJPo'
    },
    {
        id: 'overhead-cable-extentions',
        title: 'Overhead Cable Extentions',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/ns-RGsbzqok'
    },
    {
        id: 'cable-onearm-push-down',
        title: 'Cable Onearm Push Down',
        sets: 3,
        reps: 12,
        muscle:'Triceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '4 X 10-12',
        advanced: '5 X 12',
        videolink: 'https://www.youtube.com/embed/Zl46Cxc4DDs'
    },
    {
        id: 'dumbbell-biceps-curls',
        title: 'Dumbbell Biceps Curls',
        sets: 3,
        reps: 12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/ykJmrZ5v0Oo'
    },
    {
        id: 'dumbbell-hammer-curls',
        title: 'Dumbbell Hammer Curls',
        sets: 4,
        reps: 10-12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/zC3nLlEvin4'
    },
    {
        id: 'ez-bar-curls',
        title: 'Ez Bar Curls',
        sets: 4,
        reps: 10-12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/kwG2ipFRgfo'
    },
    {
        id: 'inclined-dumbbell curls',
        title: 'Inclined Dumbbell Curls',
        sets: 4,
        reps: 10-12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/soxrZlIl35U'
    },
    {
        id: 'dumbbell-preacher-curls',
        title: 'Dumbbell Preacher Curls',
        sets: 4,
        reps: 10-12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/DoCWeUBA0Gs'
    },
    {
        id: 'barbell-biceps-curls',
        title: 'Barbell Biceps Curls',
        sets: 4,
        reps: 10-12,
        muscle:'Biceps',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 12',
        intermediate: '4 X 15',
        advanced: '4 X 20',
        videolink: 'https://www.youtube.com/embed/LY1V6UbRHFM'
    },
    // {
    //     id: 'close-grip-pull-up',
    //     title: 'Close Grip Pull Up',
    //     sets: 3,
    //     reps: 10-15,
    //     muscle:'Forearms',
    // },
    // {
    //     id: 'dumbbell-one-arm-reverse-wrist-curl',
    //     title: 'Dumbbell One Arm Reverse Wrist Curl',
    //     sets: 3,
    //     reps: 10-15,
    //     muscle:'Forearms',
    // },
    // {
    //     id: '',
    //     title: '',
    //     sets: 3,
    //     reps: 12,
    //     muscle:'Forearms',
    // },
    // {
    //     id: '',
    //     title: '',
    //     sets: 3,
    //     reps: 12,
    //     muscle:'Forearms',
    // },
    // {
    //     id: '',
    //     title: '',
    //     sets: 3,
    //     reps: 12,
    //     muscle:'Forearms',
    // },
    // {
    //     id: '',
    //     title: '',
    //     sets: 3,
    //     reps: 12,
    //     muscle:'Forearms',
    // },
    {
        id: 'leg-press',
        title: 'Leg Press',
        sets: 3,
        reps: 12,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/oujca3_Shgw'
    },
    {
        id: 'squat',
        title: 'Squat',
        sets: 4,
        reps: 25,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/6AEDbzzFGsM'
    },
    {
        id: 'calf-raise',
        title: 'Calf Raise',
        sets: 5,
        reps: 12,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/gwLzBJYoWlI'
    },
    {
        id: 'weighted-squat',
        title: 'Weighted Squat',
        sets: 3,
        reps: 12,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/MVMNk0HiTMg'
    },
    {
        id: 'leg-extension',
        title: 'Leg Extension',
        sets: 4,
        reps: 12,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/YyvSfVjQeL0'
    },
    {
        id: 'leg-curl',
        title: 'Leg Curl',
        sets: 4,
        reps: 12,
        muscle:'Legs',
        desc: 'Lie face up on a flat bench, and grip a barbell with the hands slightly wider than shoulder-width. Press the feet into the ground and the hips into the bench while lifting the bar off the rack. Slowly lower the bar to the chest by allowing the elbows to bend out to the side. Stop when the elbows are just below the bench, and press feet into the floor to press the weight straight up to return to the starting position.',
        beginner: '3 X 8',
        intermediate: '3 X 12',
        advanced: '4 x 10-12',
        videolink: 'https://www.youtube.com/embed/ELOCsoDSmrg'
    },


]